### ISSUE TITLE
Running Tests Locally Not Working

### ISSUE THREAD

**Issue by toddmeinershagen** [aspnet/HttpClientFactory#192] opened 2018-10-15 21:13 UTC
For some reason I am not able to run the test suite locally within Visual Studio -- it just hangs until I cancel.  Is there a script I need to run or manual steps that need to be done in order to make that work?

I am working on determining what is wrong with the AddPolicy() extension method when adding proactive policies such as Policy.TimeoutAsync.  I have an existing factory that when using Policy.TimeoutAsync, it does not allow the HttpClient.GetAsync method to run it just consistently times out.  

I think it has something to do with improper async/await handling in the message handler set up.  I noticed in the codebase that there are missing async and await operators, but without a test suite, I cannot confirm that this will cause issues or even fix potential existing issues.

Thoughts?

**Comment by Tratcher** [comment] 2018-10-15 21:34
See https://github.com/aspnet/AspNetCore/blob/master/CONTRIBUTING.md#contributing-code-and-content

**Comment by rynowak** [comment] 2018-10-15 23:38
I have not seen any failures like this in the past, and there is no special environment setup required.  If it's hanging can you try attaching the process and getting a call stack?

**Comment by reisenberger** [comment] 2018-10-16 19:06
Opened an issue on the Polly repo, https://github.com/App-vNext/Polly/issues/518, for the report of `TimeoutPolicy` causing hangs with `HttpClientFactory`: but I cannot reproduce the issue.

**Comment by natemcmaster** [comment] 2018-11-16 17:19
Closing because we haven't had problems running tests locally. If you're still having issues, please open a new bug on the new repo for this project: https://github.com/aspnet/Extensions

**Closed as completed by natemcmaster** 2018-11-16 17:19 UTC
